### ISSUE TITLE
How do I see planet.opensuse.org locally?

### ISSUE THREAD

**Issue by Ana06** [openSUSE/planet.opensuse.org#65]
I didn't find any documentation.

I have tried running update.sh and write.sh. But what I get looks broken:

![image](https://user-images.githubusercontent.com/16052290/38086834-2d73dda4-3356-11e8-91e5-722031799a4f.png)

When running the update command I just get complains with feeds that are broken, for the write command I get:

![image](https://user-images.githubusercontent.com/16052290/38086875-4bab2368-3356-11e8-939a-62e5185f2217.png)

What I am doing wrong? :sob: Some documentation would be nice. Or if someone tell me how to do it I can also add the documentation :joy:

**Comment by Ana06** [comment]
@pbleser do you have any insight that can help me here? :pray:

**Comment by cboltz** [comment]
Your screenshot looks like you are using `file://` to access the rendered pages - with the result that JS and CSS from static.opensuse.org doesn't get included (probably because of some security setting in the browser that prevents including online files when viewing a local file)

Setup a local webserver to view the rendered pages via `http://`, and it will work :-)

**Comment by Ana06** [comment]
@cboltz thanks for your answer

> Setup a local webserver to view the rendered pages via http://, and it will work :-)

and how do I do this? :thinking:

**Comment by cboltz** [comment]
The easiest way (for testing, not recommended for production setups) is

```
cd $whereever/planet.opensuse.org/website/
python -m SimpleHTTPServer 8080
```

Then open `http://localhost:8080` in your browser.

A more common way ;-) is to setup Apache or nginx and to configure the planet.opensuse.org/website/ directory as DocumentRoot. (Your question sounds like you are not familiar with doing this - if you need help, feel free to ask in #opensuse-admin whenever you see me online.)

(CC @ccboltz to get notification mails for my own comments)

**Comment by vioan** [comment]
@Ana06 or you can just use Caddy [https://caddyserver.com/tutorial](url) 😄 instead of Apache/NGINX setup

**Comment by vinzv** [comment]
I guess this issue is fixed. Please someone close it.

**Comment by Ana06** [comment]
@vinzv 

> I guess this issue is fixed. Please someone close it.

I am not that sure it is fixed, as I think how to set up the project should be documented. However, it makes sense to do that with https://github.com/openSUSE/planet.opensuse.org/issues/69, so I agree we can close it. :wink:
