### ISSUE TITLE
Modernization of planet.opensuse.org

### ISSUE THREAD

**Issue by Ana06** [openSUSE/planet.opensuse.org#69]
I am speaking about the appearance, doing something similar to what haven been done in https://software.opensuse.org, but also changing the technology by a more modern one and documenting how to set it up. :smile:

**Comment by TheRealBro** [comment]
"Wer macht, hat Recht!" :+1: 
(Go on.)
(Be nice and inform $users)
(As long as the feed-urls from users are still readable, I don't see any issues)

**Comment by LelCP** [comment]
I started doing that few days ago but python2 defeated me, maybe we could find something that is newer or at least working?

**Comment by LelCP** [comment]
Had a better look at how all that stuff fits together and quickly drafted this:
![screenshot](https://user-images.githubusercontent.com/30577011/38160730-5ef4eab8-34c2-11e8-9798-5f89734f4e97.png)
There are some issues with rawdog, but gonna update it later to have a way to run all of the current plugins still.

**Comment by hellcp** [comment]
@Ana06 hm, I was defeated by undefeated demons of python2 and later ruby. At first I tried using rawdog still, but that is really broken with our plugins and newer releases, and there is really no point to fixing old python2 ghosts. Then I tried using planet pluto + jekyll and further modifying it to include support for more config options to fit the fact that we want the feeds to be language specific, however back then (it was like a year ago) my lack of knowledge of ruby clearly showed up through that process. 

Some tidbits that might be useful in development are https://gist.github.com/rkitover/12a55e5ee45ee18ba40dcd6364cc6242 made by kit which translates rawdog feeds into planet pluto feeds, although I can't find anything relevant to actual design of the pages, but considering it was generated in a very simplistic fashion, it will not be hard to replicate if you ever need help with that.

If you don't have the time, I might come back to this soon, however I feel like somebody more qualified should have a look at all of this and draw conclusions I never could.

**Comment by vinzv** [comment]
How's it going with this one? Any chance that we could get a more modern look for planet-o-o or even a migration to something different?

**Comment by hellcp** [comment]
I have the ruby part basically ready, I just need to filter through the existing feeds, they do throw quite a few errors and the new code doesn't particularly like that.

I'm working on html and feeds as well, from what I can tell, feeds per language won't be possible yet, will have to talk about that with upstream

**Comment by hellcp** [comment]
That's my progress on day 1: https://github.com/hellcp/planet-o-o, feel free to check it out and let me know what needs improvements

**Comment by vinzv** [comment]
Could not get it to run fully locally: 
![Screenshot_20191231_202738](https://user-images.githubusercontent.com/74432/71631962-17dfe400-2c0c-11ea-8569-1f0e0db3b9eb.png)

But judging with the screenshots from Discord it looks good so far. I like the small features like "member" and "irc nick".

**Comment by hellcp** [comment]
Ah, you need to run `update.sh` script first

Those features were inherited from the current version (although they were hidden for whatever reason)

**Comment by vinzv** [comment]
Ah, now (and after installing nokogiri) it works! First observations that came up:

**Pagewidth and space usage (at 1920x1080px)**
The whole container has 1140px which is similar to wiki-o-o at 1100px. But only 760px are used for the content. The left sidebar only has the hackergotchi, which is kinda huge and in addition has huge padding to the left. The right sidebar has no content at all.

The main content column is wasting quite some space imho for not so important stuff like current day and date. It's good to have it as some separator but not at that size. So why not condense everything a bit:
![Screenshot_20191231_232728](https://user-images.githubusercontent.com/74432/71635467-271f5b80-2c25-11ea-91b1-c4bd0ebe5e30.png)


**Length of posts**
Sometimes posts are quite long, may it be by text or by many images. I would not cut off those by a hard _» Read more_ link but maybe we could add some wrapper that extends a post without having the whole page to be reloaded?

**Comment by hellcp** [comment]
Yeah, for articles it's usually better to keep them narrow, because it's much harder to follow text when the lines are very long. You might notice how much easier it is to read articles with this design compared to the current Planet openSUSE design.

I don't really mind the calendar being this big, considering it only shows up once for all the articles for any given day. It might be a good idea to minimize the fonts so they aren't that big though.

The length of posts is troublesome, considering it isn't easy to cut off html in any arbitrary place, I will see what can be done

**Comment by vinzv** [comment]
I get the width issues with texts and can for sure live with that. Headlines in general are a bit big which causes them to wrap. Maybe that's something to chance.

Regarding length of posts and their cut off this one might help: https://codepen.io/joezimjs/pen/bLRMom
Just give every post a maximum overflow space and everything outside just gets show at slide down.

**Comment by hellcp** [comment]
Yup, I'm aware of css solutions, they are fun :D

**Comment by vinzv** [comment]
Planet is modernized apparently. Let's close this.

**Comment by Ana06** [comment]
Although it hasn't been modernized in this repository, but in https://github.com/openSUSE/planet-o-o
I don't know why though. Maybe this repo should be just deleted :thinking:

Btw, @hellcp great job! :cupid:

**Comment by hellcp** [comment]
At least it would be good to archive it ;)

**Comment by cboltz** [comment]
I added a link to the new repo in README.md and also updated the repo description to point there.

Archiving this repo is a good idea, I'll do that in a minute ;-)
